// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_peripheral_receive              11
#define gattdb_peripheral_transmit             14
#define gattdb_stream_mode                     17
#define gattdb_device_name                     21
#define gattdb_ota_control                     26
#define gattdb_cgm_measurement                 29
#define gattdb_cgm_feature                     32
#define gattdb_cgm_status                      34
#define gattdb_cgm_session_start_time          36
#define gattdb_cgm_session_run_time            38
#define gattdb_record_access_control_point         40
#define gattdb_cgm_specific_ops_control_point         43
#define gattdb_bond_management_control_point         47
#define gattdb_bond_management_feature         49
#define gattdb_manufacturer_name_string         52
#define gattdb_model_number_string             54
#define gattdb_serial_number_string            56
#define gattdb_hardware_revision_string         58
#define gattdb_firmware_revision_string         60
#define gattdb_software_revision_string         62
#define gattdb_system_id                       64
#define gattdb_ieee_11073_20601_regulatory_certification_data_list         66
#define gattdb_pnp_id                          68

#endif
